name: Java CI with JUnit, BDD, and Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: "Sr@vani9394"
          MYSQL_DATABASE: "weather"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s
          --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file spring_mysql_api/pom.xml

      - name: Run JUnit tests
        run: mvn test --file spring_mysql_api/pom.xml

      - name: Build Docker image
        run: |
          docker build -t sravanipodapati/spring_mysql_api-spring-app . -f spring_mysql_api/Dockerfile

      - name: Push Docker image to Docker Hub
        env:
         DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
         DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
         # Non-interactive Docker login using token
         docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN"
         docker tag sravanipodapati/spring_mysql_api-spring-app $DOCKERHUB_USERNAME/spring_mysql_api-spring-app
         docker push $DOCKERHUB_USERNAME/spring_mysql_api-spring-app